// src/pages/HomePage.tsx

import { useState, useEffect } from 'react';
import { useAccount } from 'wagmi';
import { createPublicClient, http, formatUnits } from 'viem';
import { base } from 'viem/chains';
import { Link } from 'react-router-dom';

import { raindropContractAddress, raindropContractABI } from '../contracts/info';
import './HomePage.css'; // For styling our table

// Define a type for our raindrop data for TypeScript
type Raindrop = {
  raindropId: string;
    token: `0x${string}`;
      totalAmount: bigint;
      };

      // Create a public client to read from the blockchain
      const publicClient = createPublicClient({
        chain: base,
          transport: http(),
          });

          export function HomePage() {
            const { address, isConnected } = useAccount();
              const [raindrops, setRaindrops] = useState<Raindrop[]>([]);
                const [isLoading, setIsLoading] = useState(false);
                  const [error, setError] = useState('');

                    useEffect(() => {
                        const fetchRaindrops = async () => {
                              if (!address) return; // Don't fetch if no user is connected

                                    setIsLoading(true);
                                          setError('');
                                                setRaindrops([]);

                                                      try {
                                                              // Fetch the logs for the RaindropCreated event, filtered by the host address
                                                                      const logs = await publicClient.getLogs({
                                                                                address: raindropContractAddress,
                                                                                          event: {
                                                                                                      type: 'event',
                                                                                                                  name: 'RaindropCreated',
                                                                                                                              inputs: [
                                                                                                                                            { type: 'string', name: 'raindropId', indexed: true },
                                                                                                                                                          { type: 'address', name: 'host', indexed: true },
                                                                                                                                                                        { type: 'address', name: 'token', indexed: true },
                                                                                                                                                                                      { type: 'uint256', name: 'totalAmount' },
                                                                                                                                                                                                    { type: 'uint256', name: 'scheduledTime' },
                                                                                                                                                                                                                ],
                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                    args: {
                                                                                                                                                                                                                                                host: address, // This is the crucial filter
                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                    fromBlock: 1n, // Search from the beginning of the chain. For production, use a more recent block.
                                                                                                                                                                                                                                                                              toBlock: 'latest',
                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                              // Map the logs to a more usable format
                                                                                                                                                                                                                                                                                                      const userRaindrops = logs.map((log) => log.args as Raindrop);
                                                                                                                                                                                                                                                                                                              setRaindrops(userRaindrops);

                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                            console.error("Error fetching raindrops:", e);
                                                                                                                                                                                                                                                                                                                                    setError("Failed to fetch raindrops. Please try again.");
                                                                                                                                                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                                                                                                                                                  setIsLoading(false);
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                fetchRaindrops();
                                                                                                                                                                                                                                                                                                                                                                  }, [address]); // Re-run this effect when the connected account changes

                                                                                                                                                                                                                                                                                                                                                                    if (!isConnected) {
                                                                                                                                                                                                                                                                                                                                                                        return <p>Please connect your wallet to see your dashboard.</p>;
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                            if (isLoading) {
                                                                                                                                                                                                                                                                                                                                                                                return <p>Loading your raindrops...</p>;
                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                    if (error) {
                                                                                                                                                                                                                                                                                                                                                                                        return <p style={{ color: 'red' }}>{error}</p>;
                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                      <div className="dashboardHeader">
                                                                                                                                                                                                                                                                                                                                                                                                              <h2>My Raindrops Dashboard</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                      <Link to="/create" className="createButton">Create New Raindrop</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  {raindrops.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>You haven't created any raindrops yet.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <table className="raindropsTable">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th>Raindrop ID</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <th>Token Address</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>Total Amount</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {raindrops.map((raindrop) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tr key={raindrop.raindropId}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link to={`/raindrop/${raindrop.raindropId}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {raindrop.raindropId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td>{raindrop.token}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* formatUnits converts the large number back to a readable format */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td>{formatUnits(raindrop.totalAmount, 18)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }